const CACHE="catalogue-l4d2-20261009-146";
const SHELL=["/ui-runtime.js?v=20261009-146","/ui-current.css?v=20261009-146","/","/app.js?v=20261009-146","/polish.css?v=20260919-100","/layout-air-v80.css?v=20260919-114","/bootstrap-data.js?v=20260810-3","/campaign-icon.jpg","/welcome-cover-centered-v145.png","/l4d2-final-192-v52.png","/l4d2-splash-safe-512-v101.png?v=20260823-101","/l4d2-maskable-512-v53.png?v=20260823-105","/steam-icon-exact-v124.svg","/chat-icon-top-v127.svg","/manifest.webmanifest?v=20260823-105","/cloud-backup.js?v=20261009-146","/vendor/supabase/supabase.js?v=1"];
const STATIC_DESTINATIONS=new Set(["style","script","image","font","manifest"]);
const LEGACY_STEAM_ICONS=new Set(["/steam-icon.png","/steam-icon-fast.svg","/steam-icon-user.png"]);
const sameOrigin=request=>new URL(request.url).origin===self.location.origin;
const cacheResponse=(request,response)=>{if(response&&response.ok){const copy=response.clone();caches.open(CACHE).then(cache=>cache.put(request,copy));}return response;};
self.addEventListener("install",event=>event.waitUntil(caches.open(CACHE).then(cache=>cache.addAll(SHELL)).then(()=>self.skipWaiting())));
self.addEventListener("activate",event=>event.waitUntil((async()=>{const keys=await caches.keys();const previous=keys.filter(key=>key!==CACHE);const hadPreviousAppCache=previous.some(key=>key.startsWith("catalogue-l4d2-"));await Promise.all(previous.map(key=>caches.delete(key)));await self.clients.claim();if(hadPreviousAppCache){const windows=await self.clients.matchAll({type:"window",includeUncontrolled:true});await Promise.all(windows.map(client=>client.navigate(client.url).catch(()=>null)));}})()));
self.addEventListener("fetch",event=>{const request=event.request;if(request.method!=="GET"||new URL(request.url).pathname.startsWith("/api/drive-backup"))return;if(sameOrigin(request)&&LEGACY_STEAM_ICONS.has(new URL(request.url).pathname)){const target=new Request(new URL("/steam-icon-exact-v124.svg",self.location.origin));event.respondWith(caches.match(target).then(hit=>hit||fetch(target,{cache:"no-store"}).then(response=>cacheResponse(target,response))));return;}if(sameOrigin(request)&&STATIC_DESTINATIONS.has(request.destination)){event.respondWith(caches.match(request).then(hit=>hit||fetch(request,{cache:"no-store"}).then(response=>cacheResponse(request,response))));return;}event.respondWith(fetch(request,{cache:"no-store"}).then(response=>cacheResponse(request,response)).catch(()=>caches.match(request).then(hit=>hit||caches.match("/"))));});
