package com.wokgui.l4d2;
import android.app.*; import android.os.*; import android.content.*; import android.content.res.ColorStateList; import android.graphics.Color; import android.graphics.Typeface; import android.net.Uri; import android.view.*; import android.webkit.*; import android.widget.*; import java.io.*;
public class MainActivity extends Activity {
 private WebView web; private FrameLayout root; private View loading; private long started; private boolean revealed;
 private ValueCallback<Uri[]> fileCallback; private byte[] pendingExport;
 private int dp(float n){return Math.round(n*getResources().getDisplayMetrics().density);}
 @Override public void onCreate(Bundle state){super.onCreate(state);started=SystemClock.uptimeMillis();
 int bg=Color.parseColor("#F6EFE2");getWindow().setStatusBarColor(bg);getWindow().setNavigationBarColor(bg);getWindow().getDecorView().setSystemUiVisibility(View.SYSTEM_UI_FLAG_LIGHT_STATUS_BAR|View.SYSTEM_UI_FLAG_LIGHT_NAVIGATION_BAR);
 root=new FrameLayout(this);root.setBackgroundColor(bg);setContentView(root);
 web=new WebView(this);web.setBackgroundColor(bg);root.addView(web,new FrameLayout.LayoutParams(-1,-1));
 root.setOnApplyWindowInsetsListener((v,insets)->{root.setPadding(insets.getSystemWindowInsetLeft(),insets.getSystemWindowInsetTop(),insets.getSystemWindowInsetRight(),insets.getSystemWindowInsetBottom());return insets;});root.requestApplyInsets();
 LinearLayout cover=new LinearLayout(this);cover.setOrientation(LinearLayout.VERTICAL);cover.setGravity(Gravity.CENTER);cover.setBackgroundColor(bg);
 ImageView icon=new ImageView(this);icon.setImageDrawable(getApplicationInfo().loadIcon(getPackageManager()));cover.addView(icon,new LinearLayout.LayoutParams(dp(112),dp(112)));
 TextView title=new TextView(this);title.setText("L4D2");title.setTextSize(26);title.setTypeface(Typeface.DEFAULT,Typeface.BOLD);title.setTextColor(Color.parseColor("#171723"));LinearLayout.LayoutParams tp=new LinearLayout.LayoutParams(-2,-2);tp.topMargin=dp(16);cover.addView(title,tp);
 ProgressBar bar=new ProgressBar(this,null,android.R.attr.progressBarStyleHorizontal);bar.setIndeterminate(true);bar.setIndeterminateTintList(ColorStateList.valueOf(Color.parseColor("#7652DF")));LinearLayout.LayoutParams bp=new LinearLayout.LayoutParams(dp(192),dp(4));bp.topMargin=dp(12);cover.addView(bar,bp);loading=cover;root.addView(loading,new FrameLayout.LayoutParams(-1,-1));
 WebSettings s=web.getSettings();s.setJavaScriptEnabled(true);s.setDomStorageEnabled(true);s.setDatabaseEnabled(true);s.setAllowFileAccess(false);s.setAllowContentAccess(true);s.setMediaPlaybackRequiresUserGesture(false);s.setUserAgentString(s.getUserAgentString()+" WokguiNative/1.0");CookieManager.getInstance().setAcceptCookie(true);
 web.addJavascriptInterface(new NativeBridge(),"NativeFiles");
 web.setWebViewClient(new WebViewClient(){
 @Override public WebResourceResponse shouldInterceptRequest(WebView v,WebResourceRequest req){Uri u=req.getUrl();if(!"catalogue-l4d2.vercel.app".equals(u.getHost())||!"GET".equals(req.getMethod()))return null;String path=u.getPath();if(path==null||path.startsWith("/api/")||path.contains(".."))return null;if(path.equals("/"))path="/index.html";try{InputStream stream=getAssets().open("site"+path);String ext=MimeTypeMap.getFileExtensionFromUrl(path);String mime=MimeTypeMap.getSingleton().getMimeTypeFromExtension(ext);if(path.endsWith(".js"))mime="application/javascript";if(path.endsWith(".webmanifest"))mime="application/manifest+json";if(mime==null)mime="application/octet-stream";return new WebResourceResponse(mime,"UTF-8",stream);}catch(IOException ignored){return null;}}
 @Override public boolean shouldOverrideUrlLoading(WebView v,WebResourceRequest req){Uri u=req.getUrl();if("https".equals(u.getScheme())&&"catalogue-l4d2.vercel.app".equals(u.getHost()))return false;if(req.isForMainFrame()){try{startActivity(new Intent(Intent.ACTION_VIEW,u));}catch(Exception e){Toast.makeText(MainActivity.this,"Impossible dÃ¢â‚¬â„¢ouvrir ce lien",Toast.LENGTH_SHORT).show();}return true;}return false;}
 @Override public void onPageFinished(WebView v,String url){if("catalogue-l4d2.vercel.app".equals(Uri.parse(url).getHost()))v.evaluateJavascript("(()=>{const imgs=[...document.images].filter(i=>i.getBoundingClientRect().top<innerHeight);const ready=()=>requestAnimationFrame(()=>requestAnimationFrame(()=>NativeFiles.ready()));Promise.race([Promise.all(imgs.map(i=>i.complete?Promise.resolve():new Promise(r=>{i.addEventListener('load',r,{once:true});i.addEventListener('error',r,{once:true})}))),new Promise(r=>setTimeout(r,2200))]).then(ready)})()",null);}
 @Override public void onReceivedError(WebView v,WebResourceRequest r,WebResourceError e){if(r.isForMainFrame()){reveal();Toast.makeText(MainActivity.this,"Chargement impossible. VÃƒÂ©rifie la connexion.",Toast.LENGTH_LONG).show();}}
 });
 web.setWebChromeClient(new WebChromeClient(){@Override public boolean onShowFileChooser(WebView v,ValueCallback<Uri[]> cb,FileChooserParams p){if(fileCallback!=null)fileCallback.onReceiveValue(null);fileCallback=cb;try{Intent pick=p.createIntent();pick.addCategory(Intent.CATEGORY_OPENABLE);startActivityForResult(pick,10);return true;}catch(Exception e){fileCallback=null;return false;}}});
 if(state==null||web.restoreState(state)==null)web.loadUrl("https://catalogue-l4d2.vercel.app/?native=1");else web.postDelayed(this::reveal,650);
 }
 private void reveal(){runOnUiThread(()->{if(revealed||isFinishing()||isDestroyed())return;long delay=Math.max(0,650-(SystemClock.uptimeMillis()-started));web.postDelayed(()->web.postVisualStateCallback(1,new WebView.VisualStateCallback(){@Override public void onComplete(long id){if(revealed||isDestroyed())return;revealed=true;root.removeView(loading);loading=null;}}),delay);});}
 public class NativeBridge {@JavascriptInterface public void ready(){reveal();}
 @JavascriptInterface public void save(String data,String name,String mime){try{byte[] decoded=android.util.Base64.decode(data,android.util.Base64.DEFAULT);runOnUiThread(()->{if(pendingExport!=null)return;pendingExport=decoded;Intent save=new Intent(Intent.ACTION_CREATE_DOCUMENT);save.addCategory(Intent.CATEGORY_OPENABLE);save.setType(mime);save.putExtra(Intent.EXTRA_TITLE,name);try{startActivityForResult(save,11);}catch(Exception e){pendingExport=null;Toast.makeText(MainActivity.this,"Enregistrement indisponible",Toast.LENGTH_LONG).show();}});}catch(Exception ignored){}}
 }
 @Override protected void onActivityResult(int req,int result,Intent data){super.onActivityResult(req,result,data);if(req==10&&fileCallback!=null){fileCallback.onReceiveValue(WebChromeClient.FileChooserParams.parseResult(result,data));fileCallback=null;}if(req==11){byte[] bytes=pendingExport;pendingExport=null;if(result==RESULT_OK&&data!=null&&data.getData()!=null&&bytes!=null){try(OutputStream stream=getContentResolver().openOutputStream(data.getData())){stream.write(bytes);Toast.makeText(this,"Sauvegarde enregistrÃƒÂ©e",Toast.LENGTH_SHORT).show();}catch(Exception e){Toast.makeText(this,"Ãƒâ€°chec de lÃ¢â‚¬â„¢enregistrement",Toast.LENGTH_LONG).show();}}}}
 @Override public void onBackPressed(){if(web.canGoBack())web.goBack();else super.onBackPressed();}
 @Override protected void onSaveInstanceState(Bundle b){web.saveState(b);super.onSaveInstanceState(b);}
 @Override protected void onPause(){web.onPause();CookieManager.getInstance().flush();super.onPause();}
 @Override protected void onResume(){super.onResume();if(web!=null)web.onResume();}
 @Override protected void onDestroy(){if(fileCallback!=null)fileCallback.onReceiveValue(null);root.removeAllViews();web.destroy();super.onDestroy();}
}
